### PR TITLE
coverage-percentage

### PR DESCRIPTION
**Pull request by sveinungkb**

### CODE REVIEW

**Comment by xolvo** [comment]
I'm very pleased, that such a small script gets your attention and you've made this PR.
But I think it's better reconsider usage of this utility and switch to Maven and native JaCoCo coverage support in TeamCity 9.

Although, manual percentage calculation is not recommended https://confluence.jetbrains.com/display/TCD9/How+To...#HowTo...-ImportcoverageresultsinTeamCity
And finally, I didn't find any information about `CodeCoverageAbsLPercentage` here https://confluence.jetbrains.com/display/TCD9/Custom+Chart#CustomChart-predefinedStatisticsKeys

**Comment by sveinungkb** [comment]
Haha, always fun when someone finds your work!
Jacoco still doesn't work properly with Android, so we're left to misc hacks and then generating the report files manually, so this was perfect for me. I was going to write it up myself, but it was convenient that you had done the job for me :+1: 
I'll rename percentage, I had added all of these to custom statistics keys in my `server.xml` as I didn't know they were predefined, thanks!

**Comment by xolvo** [comment]
Understand your problem with Android.

But still could not get why do you calculate these percentage? TeamCity will calculate them for you based on `CodeCoverageAbsLCovered` and `CodeCoverageAbsLTotal` for example.

And if commit 7f0d7ce is your last fix, it still has custom key with `Percentage` at the end. It should be `CodeCoverageL` not `CodeCoverageLPercentage`. Or do you want them to be custom on purpose?

**Comment by sveinungkb** [comment]
Aha, I was not aware of that! I probably should've tested before I did it manually.. Closing PR, obsolete, but I'll still put your scripts to use!

**Pull request closed without merging**
